### ISSUE TITLE
Incorrect remove alternative example in README.md

### ISSUE THREAD

**Issue by karlding** [vkhatri/chef-alternatives#1]
For the **LWRP remove alternative** example:

```ruby
alternatives 'python install 3' do
  link_name 'python'
  path '/usr/bin/python3'
  priority 101
  action :install
end
```

It looks like the **LWRP install alternative** example was copied over. I assume the example needs to be corrected, and `action` should be `:remove`?

**Comment by vkhatri** [comment]
@karlding 👍 

Updated README.
