### ISSUE TITLE
cookbook version should be bumped

### ISSUE THREAD

**Issue by gagomes** [vkhatri/chef-alternatives#3]
The previous version before @tas50's refactoring was a version 0.2.0. The current version remains at 0.2.0. This can cause pipelines to fail to consume the latest versions of this cookbook because of cookbook freezer options which prevent same version upload.

**Comment by vkhatri** [comment]
@gagomes Released v0.3.0 to supermarket.

**Comment by gagomes** [comment]
Thank you, @vkhatri! Much appreciated for the quick turn around :)
